name: echo_logger
description: "Echo Logger is a powerful and flexible logging utility for Flutter that allows developers to log messages with custom tags, colors, and severity levels. It is designed to make debugging and monitoring easier by providing a highly customizable logging experience."
version: 0.0.3
homepage: https://github.com/mostafaemara/echo

environment:
  sdk: '>=2.12.0 <4.0.0' 
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

   plugin:
     platforms:
        android:
          package: com.mse.echo_logger
          pluginClass: EchoLoggerPlugin
        ios:
          pluginClass: EchoLoggerPlugin
        web:
           pluginClass: EchoLoggerWeb
           fileName: echo_logger_web.dart